name: Github Pages Cron Release - Branch

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
    #   - name: Cache dependencies
    #     id: cache
    #     uses: actions/cache@v4
    #     with:
    #       path: |
    #         ./node_modules
    #         ./client/node_modules
    #       key: modules-${{ hashFiles('package-lock.json') }}
      - name: npm install
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          make clean-npm
      - name: npm test
        run: |
          npm test
      - name: npm rebuild
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/'
  Release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Build

    permissions:
      id-token: write
      pages: write
      contents: write

    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
    #   - name: Cache dependencies
    #     id: cache
    #     uses: actions/cache@v4
    #     with:
    #       path: |
    #         ./node_modules
    #         ./client/node_modules
    #       key: modules-${{ hashFiles('package-lock.json') }}
      - name: npm install
        # if: steps.cache.outputs.cache-hit != 'true'
        run: |
          make clean-npm
      - name: npm test
        run: |
          npm test
      # - name: npm build
      #   run: |
      #     npm run build
      # - name: npm deploy
      #   run: |
      #     git config --global user.name "Alex Reiff"
      #     git config --global user.email "alex.reiff@ibm.com"
      #     npm run deploy
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      - name: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build/'
          # enable_jekyll: true