name: Release-Pipeline

# Trigger on push(merge) to main branch
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-terraform-release-pipeline:
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-release.yml@v1.21.9
    secrets: inherit
